server:
  port: 8081

spring:
  application:
    name: sairam
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/saidb
    username: postgres
    password: 0367
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
